# Generated by Django 4.0 on 2021-12-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0002_cleaningteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingTeam',
            fields=[
                ('group_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Supervisor', models.CharField(max_length=50)),
                ('Assigned_Rooms', models.IntegerField()),
                ('Assigned_Patients', models.CharField(max_length=50)),
                ('shift_time', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='Assigned_Patient',
            new_name='Assigned_Patients',
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='nurses',
            name='Password',
        ),
        migrations.AddField(
            model_name='nurses',
            name='Salary',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
