# Generated by Django 4.0 on 2021-12-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0004_alter_nursingteam_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
