# Generated by Django 4.0 on 2021-12-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0005_alter_nurses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurses',
            name='group_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.nursingteam'),
        ),
    ]
