# Generated by Django 4.0 on 2021-12-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0006_alter_nurses_group_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurses',
            old_name='group_number',
            new_name='group_number_nurses',
        ),
    ]
