# Generated by Django 4.0 on 2021-12-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0007_rename_group_number_nurses_group_number_nurses'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingSupervision',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=100)),
                ('Responsible_group_number', models.IntegerField()),
                ('Salary', models.IntegerField(max_length=50, null=True)),
            ],
        ),
    ]
