# Generated by Django 4.0 on 2021-12-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0008_nursingsupervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingsupervision',
            name='Responsible_group_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.nursingteam'),
        ),
    ]
