# Generated by Django 4.0 on 2021-12-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0010_alter_nurses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingsupervision',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
