# Generated by Django 4.0 on 2021-12-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0011_alter_nursingsupervision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingsupervision',
            name='Id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
