# Generated by Django 4.0 on 2021-12-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0012_alter_nursingsupervision_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningteam',
            old_name='Assigned_Room',
            new_name='Assigned_Rooms',
        ),
        migrations.RenameField(
            model_name='nurses',
            old_name='Assigned_Room',
            new_name='Assigned_Rooms',
        ),
        migrations.RemoveField(
            model_name='cleaningteam',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='cleaningteam',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='cleaningteam',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='cleaningteam',
            name='shift_time',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='cleaningteam',
            name='group_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CleaningSupervision',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=100)),
                ('Salary', models.IntegerField(max_length=50, null=True)),
                ('Responsible_group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.cleaningteam')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningIndividuals',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Supervisor', models.CharField(max_length=50)),
                ('Assigned_Rooms', models.IntegerField()),
                ('Salary', models.IntegerField(max_length=50, null=True)),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.cleaningteam')),
            ],
        ),
    ]
