# Generated by Django 4.0 on 2021-12-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0013_rename_assigned_room_cleaningteam_assigned_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
