# Generated by Django 4.0 on 2021-12-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0014_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('Phone_number', models.IntegerField(max_length=15)),
                ('Contact_relatives', models.CharField(max_length=200)),
                ('Medical_record', models.URLField(verbose_name='Click here for medical record')),
            ],
        ),
    ]
