# Generated by Django 4.0 on 2021-12-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0015_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('Phone_number', models.IntegerField(max_length=15)),
                ('Assigned_Patients', models.CharField(max_length=150)),
                ('Assigned_rooms', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='Assigned_doctor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='Assigned_room',
            field=models.IntegerField(default='0', max_length=5),
        ),
    ]
