# Generated by Django 4.0 on 2021-12-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0017_patient_x_ray_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningindividuals',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='X_ray_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
