# Generated by Django 4.0 on 2021-12-31 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0018_alter_cleaningindividuals_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingteam',
            name='Assigned_patients_Id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration_system.patient'),
        ),
    ]
