# Generated by Django 4.0 on 2021-12-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0020_alter_nursingteam_assigned_patients_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingteam',
            name='Assigned_patients_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
