# Generated by Django 4.0 on 2021-12-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0021_alter_nursingteam_assigned_patients_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingteam',
            name='Assigned_patients_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration_system.patient'),
        ),
    ]
