# Generated by Django 4.0 on 2021-12-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0022_alter_nursingteam_assigned_patients_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursingteam',
            old_name='Assigned_patients_Id',
            new_name='Assigned_patients_Nurses',
        ),
    ]
