# Generated by Django 4.0 on 2021-12-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0023_rename_assigned_patients_id_nursingteam_assigned_patients_nurses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingteam',
            name='Assigned_patients_Nurses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_system.patient'),
        ),
    ]
