# Generated by Django 4.0 on 2021-12-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_system', '0024_alter_nursingteam_assigned_patients_nurses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursingteam',
            old_name='Assigned_patients_Nurses',
            new_name='Id',
        ),
    ]
